model_names = ['sphere_with_spot', 'ellipsoid_with_cluster_on_pole', 'ellipsoid_with_lateral_cluster']
R = 1
A = 1
B = 0.5
C = (A**2 - B**2)**0.5
L = 4
mesh_micro_size = 0.02
mesh_middle_size = 0.1
mesh_macro_size = 2
element_order = 2
element_name = 'Tetrahedron'
element2D_name = 'Triangle'
steps_num = 20
